In [1]:
import numpy as np
import random
import scipy
import math

In [50]:
# K-MEANS   in   R^2

def d(a, b, m):
    w=0
    for i in range(m):
        w += (a[i]-b[i])**2
    return w

def middle(a, b, m):
    mid = []
    for i in range(n):
        mid.append((a[i]-b[i])/2)
    return mid


a = np.arange(16).reshape(4, 4)

n=4
m=4
k=3 
l=[]
c = []
klasters = {}
spisok = []
ism = 10

for i in range (k):                 # рандомный выбор центроида 
    p = random.randint(0,n-1)       # исправить возможный выбор нескольких одинаковых p
   # if l.count(a[p]) == 0:
    #    l.append(a[p])
  #  else:
   #     i -= 1
    
    ###### ValueError: The truth value of an array with more than one element is ambiguous.
    ###### Use a.any() or a.all()
    c.append(a[p])
    l.append(c[i])  ##сразу знаем индекс точки
    
for i in range (k):   #создание списка(spisok) кластеров с точками(t)
    t=[]
    t.append(l[i])
    spisok.append(t)
    
while ism > 0.1 :
    

    ism = 0
    for i in range (n):  # распределение по кластерам
        mi = 1000
        for j in range(k):
            if d(a[i],l[j],m) < mi :
                mi = d(a[i],l[j],m)
                
                # не проходит
                
                for q in range(k):
                    spisok[q].pop(i)  #удаление из всех подсписков
                spisok[j].append(a[i])      #добавление в ЭТОТ подсписок
            
    for i in range (k):   # пересчет центра масс
        dlina = len(spisok[i])  # 
        mid = spisok[i][0]
    
        for j in range(1, dlina):
            mid = middle(mid, spisok[i][j], m)
        ism += d(mid, l[i], m)
        l[i] = mid


print(k)
print(l)
print(mi)
print(ism)
    
# расстояние точек до каждого из кластеров
# минимальное расстояние обозначит принаблежность кластеру
# счет центра масс
# повтор, пока суммарное изменение не будет меньше порогового epsilon




IndexError: pop from empty list

In [26]:
print(l)
print(l[1])
print(l[1][3])
d = []
b = []
c = []
b.append(1)
d.append(b)
d.append(2)
b.append(c)
c.append(5)
d[0].append(3)
d[0].remove(c)

print (d)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([12, 13, 14, 15])]
[4 5 6 7]
7
[[1, 3], 2]


In [40]:
print(a[2])
print(l)
print(l[1])
print(l.index(a[2]))
print(l)

[ 8  9 10 11]
[array([4, 5, 6, 7]), array([12, 13, 14, 15])]
[12 13 14 15]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [46]:
c=[]
l=[]
for i in range (k):                 # рандомный выбор центроида 
    p = random.randint(0,n-1)
    c.append(a[p])
    l.append(c[i])
    
print(l)
print(c)

[array([12, 13, 14, 15]), array([12, 13, 14, 15]), array([0, 1, 2, 3])]
[array([12, 13, 14, 15]), array([12, 13, 14, 15]), array([0, 1, 2, 3])]
