In [2]:
import numpy as np
import random
import scipy
import math

In [17]:
#  1   
#Создайте двумерный массив 10x3, заполненный случайными значениями.
#В каждой строке выберите значение, наиболее близкое к 0.5
a = np.random.random((10,3))
i=0

print("Array:")
print(a)
print("")
print("Numbers:")

for i in range(10):
    if (abs(a[i,0]-0.5) >= abs(a[i,1]-0.5)):
        if abs(a[i,2] - 0.5) >= abs(a[i,1] - 0.5):
            print(a[i,1])
        else:
            print(a[i,2])
    else:
        if abs(a[i,2]-0.5) >= abs(a[i,0]-0.5):
            print(a[i,0])
        else:
            print(a[i,2])


Array:
[[0.82829039 0.99827758 0.71359923]
 [0.17501521 0.02293044 0.96625305]
 [0.80489029 0.80295352 0.84744872]
 [0.49456717 0.87975356 0.41748737]
 [0.62877766 0.6145487  0.13548171]
 [0.52501494 0.10065029 0.50966503]
 [0.21074146 0.94624111 0.2848308 ]
 [0.30314812 0.46202634 0.27284051]
 [0.79613801 0.90783483 0.52294453]
 [0.24826023 0.61058604 0.35564502]]

Numbers:
0.7135992290570913
0.17501520933657055
0.8029535155783758
0.49456716859341365
0.6145487032415647
0.5096650254764507
0.28483079899867425
0.4620263359095943
0.522944526133075
0.6105860370769841


In [18]:
#   2
#Создайте двумерный массив 6x6, заполненный случайными значениями. 
#Затем сумму по каждой строке поделите на минимальный элемент
#из столбца с тем же индексом.


a = np.random.random((6,6))
print("Matrix: ")
print(a)
print("")

j=0
b=[]

for j in range(6):
    minim = a[0,j]
    for i in range(6):
        if (a[i,j] < minim):
            minim = a[i,j]
    b.append(minim)
    
print("minimum line =  " + str(b))
print("")

i=0
j=0
s=0
c=[]
for i in range(6):
    for j in range(6):
        s += a[i,j]
    c.append(s)
    s=0

print("amount line =  " + str(c))
print("")
i=0
j=0

for i in range(6):
    for j in range(6):
        a[i,j] = c[i] / b[j]
        
print("Now the matrix A is:  ")
print(a)


Matrix: 
[[0.3781217  0.26053694 0.03280237 0.39672322 0.58466575 0.35914533]
 [0.36978982 0.26487775 0.57006586 0.79386238 0.77806127 0.27441073]
 [0.84889428 0.53026554 0.84162929 0.3683138  0.41951071 0.79157456]
 [0.57009927 0.30653086 0.37067129 0.50030443 0.40616632 0.08881601]
 [0.9769299  0.59896583 0.72539922 0.54791137 0.06121383 0.99487591]
 [0.81762755 0.17541679 0.89482403 0.95101493 0.68330352 0.59962814]]

minimum line =  [0.3697898184546988, 0.17541678979596054, 0.0328023659326413, 0.3683137957089754, 0.06121382761904881, 0.08881600928689037]

amount line =  [2.0119953149340897, 3.0510678020724837, 3.800188177574406, 2.242588185246372, 3.9052960495385327, 4.121814946216095]

Now the matrix A is:  
[[  5.44091593  11.46979897  61.33689622   5.46272048  32.86831412
   22.65352081]
 [  8.25081614  17.39324842  93.01365055   8.2838814   49.8427875
   34.35267838]
 [ 10.27661657  21.66376538 115.85103908  10.31780026  62.08055149
   42.78719803]
 [  6.06449414  12.78434173  

In [19]:
# На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) 
# найдите максимальный элемент в массиве среди элементов,
# перед которыми стоит ноль.

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

mi=0
for i in range (1,7):
    if x[i-1]==0:
        if x[i] > mi :
            mi = x[i]
print(mi)
        


5


In [20]:
# Пусть заданы два массива x = np.ones(10) и 
# a = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам 
# массива x, индексы которых указаны в массиве a. В случае, если некоторый
# индекс встретился в массиве a несколько раз, прибавьте к соответствующему 
# элементу массива x число вхождений данного индекса в массив a.

x=np.ones(10)
a=np.array([0, 1, 2, 3, 5, 5, 5, 8])


print("Before: ")
print(x)

for i in range(9):
    for j in range(8):
        if a[j] == i :
            x[i] += 1
            
print("After: ")
print(x)



Before: 
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
After: 
[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [21]:
# По заданному двумерному массиву размера NxN постройте словарь, 
# ключи которого - индексы диагоналей, параллельных побочной 
# (нумерация начинается с 0), а значения - списки элементов исходного массива, 
# лежащих на соответствующих диагоналях. Решите задачу на примере массива 
# a = np.arange(16).reshape(4, 4), в результате должен получиться словарь
# {0: [0], 1: [1, 4], 2: [2, 5, 8], 3: [3, 6, 9, 12], 4: [7, 10, 13], 5: [11, 14], 6: [15]}.

a = np.arange(16).reshape(4, 4)
N=4
print("Matrix: ")
print(a)
print("")


l=[]
slov={}
i=0; j=0; k=0; p=0

for k in range(2*N-1):     #keys
    
    for i in range (N):
        for j in range (N):
            if i+j == p :
                l.append(a[i,j])
    p += 1
    slov[k] = l
    l = []

print("dict = ")
print(slov)

                    




Matrix: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

dict = 
{0: [0], 1: [1, 4], 2: [2, 5, 8], 3: [3, 6, 9, 12], 4: [7, 10, 13], 5: [11, 14], 6: [15]}


In [4]:
# K-MEANS   in   R^2

def d(a, b, m):
    w=0
    for i in range(m):
        w += (a[i]-b[i])**2
    return w

def middle(a, b, m):
    mid = []
    for i in range(n):
        mid.append((a[i]-b[i])/2)
    return mid


a = np.arange(16).reshape(4, 4)

n=4
m=4
k=3 
l=[]
klasters = {}
spisok = []
ism = 10

for i in range (k):
    p = random.randint(0,n-1)
    l.append(a[p])
    
for i in range (k):
    t=[]
    t.append(l[i])
    spisok.append(t)
    
# while ism > 0.1 :
    

    ism = 0
    for i in range (n):  # распределение по кластерам
        mi = 1000
        for j in range(k):
            if d(a[i],l[j],m) < mi :
                mi = d(a[i],l[j],m)
                
                # не проходит
                
      #          for q in range(k-1):
     #               spisok[q].remove(a[i])  #удаление из всех подсписков
      #          spisok[j].append(a[i])      #добавление в ЭТОТ подсписок
            
  #  for i in range (k):   # пересчет центра масс
    #    dlina = len(spisok[i])  # 
    #    mid = spisok[i][0]
    
   #     for j in range(1, dlina):
   #         mid = middle(mid, spisok[i][j], m)
   #     ism += d(mid, l[i], m)
   #     l[i] = mid


print(k)
    
    
# расстояние точек до каждого из кластеров
# минимальное расстояние обозначит принаблежность кластеру
# счет центра масс
# повтор, пока суммарное изменение не будет меньше порогового epsilon





3


In [28]:
print(l)
print(l[1])
print(l[1][3])

[array([4, 5, 6, 7]), array([4, 5, 6, 7]), array([4, 5, 6, 7])]
[4 5 6 7]
7


In [27]:
d = []
b = []
b.append(1)
d.append(b)
d.append(2)
d[0].append(3)

print (d)

[[1, 3], 2]
