In [7]:
import numpy as np
import random
import scipy
import math

In [37]:
#  1   
#Создайте двумерный массив 10x3, заполненный случайными значениями.
#В каждой строке выберите значение, наиболее близкое к 0.5
a = np.random.random((10,3))
i=0

print("Array:")
print(a)
print("")
print("Numbers:")

for i in range(10):
    if (abs(a[i,0]-0.5) >= abs(a[i,1]-0.5)):
        if abs(a[i,2] - 0.5) >= abs(a[i,1] - 0.5):
            print(a[i,1])
        else:
            print(a[i,2])
    else:
        if abs(a[i,2]-0.5) >= abs(a[i,0]-0.5):
            print(a[i,0])
        else:
            print(a[i,2])


Array:
[[0.45035848 0.56094311 0.7368813 ]
 [0.58145794 0.40691351 0.62391305]
 [0.77448587 0.03690024 0.0820466 ]
 [0.65197312 0.93110555 0.09948035]
 [0.9082399  0.07334767 0.44412246]
 [0.89835316 0.58924358 0.08785893]
 [0.54044813 0.31264203 0.7019777 ]
 [0.14458712 0.44413058 0.13413595]
 [0.40876464 0.17158652 0.75490514]
 [0.05550783 0.45230585 0.21305682]]

Numbers:
0.4503584773995345
0.5814579405049803
0.7744858665079534
0.6519731194869599
0.44412246437721836
0.5892435820270467
0.540448126554992
0.4441305813186932
0.40876464457454376
0.45230584544817587


In [16]:
#   2
#Создайте двумерный массив 6x6, заполненный случайными значениями. 
#Затем сумму по каждой строке поделите на минимальный элемент
#из столбца с тем же индексом.


a = np.random.random((6,6))
print("Matrix: ")
print(a)
print("")

j=0
b=[]

for j in range(6):
    minim = a[0,j]
    for i in range(6):
        if (a[i,j] < minim):
            minim = a[i,j]
    b.append(minim)
    
print("minimum line =  " + str(b))
print("")

i=0
j=0
s=0
c=[]
for i in range(6):
    for j in range(6):
        s += a[i,j]
    c.append(s)
    s=0

print("amount line =  " + str(c))
print("")
i=0
j=0

for i in range(6):
    for j in range(6):
        a[i,j] = c[i] / b[j]
        
print("Now the matrix A is:  ")
print(a)


Matrix: 
[[0.53098431 0.40041971 0.64961216 0.72881689 0.41296026 0.52768632]
 [0.86225502 0.61223991 0.10467288 0.74785053 0.09019195 0.74113859]
 [0.22371635 0.27146074 0.25782633 0.10261386 0.22045647 0.80380007]
 [0.65512726 0.40126964 0.47127801 0.80357018 0.19880961 0.88393067]
 [0.09530062 0.71655186 0.81794819 0.0746631  0.09342497 0.68064577]
 [0.68381674 0.76209206 0.20490702 0.70631796 0.2267673  0.49326803]]

minimum line =  [0.0953006195550391, 0.271460738420916, 0.1046728807296784, 0.07466309821041262, 0.09019195492094689, 0.49326803288027943]

amount line =  [3.2504796453019953, 3.158348878334217, 1.8798738261042207, 3.4139853575649166, 2.4785345162252614, 3.077169111494527]

Now the matrix A is:  
[[34.10764443 11.97403228 31.05369435 43.53529017 36.03957413  6.58968234]
 [33.14090604 11.63464336 30.17351635 42.30133699 35.01807762  6.40290606]
 [19.72572513  6.92503025 17.9595117  25.17808491 20.84303226  3.81105951]
 [35.82332805 12.57635037 32.6157581  45.72520347 37

In [23]:
# На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) 
# найдите максимальный элемент в массиве среди элементов,
# перед которыми стоит ноль.

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

mi=0
for i in range (1,7):
    if x[i-1]==0:
        if x[i] > mi :
            mi = x[i]
print(mi)
        


5


In [32]:
# Пусть заданы два массива x = np.ones(10) и 
# a = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам 
# массива x, индексы которых указаны в массиве a. В случае, если некоторый
# индекс встретился в массиве a несколько раз, прибавьте к соответствующему 
# элементу массива x число вхождений данного индекса в массив a.

x=np.ones(10)
a=np.array([0, 1, 2, 3, 5, 5, 5, 8])


print("Before: ")
print(x)

for i in range(9):
    for j in range(8):
        if a[j] == i :
            x[i] += 1
            
print("After: ")
print(x)



Before: 
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
After: 
[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [54]:
# По заданному двумерному массиву размера NxN постройте словарь, 
# ключи которого - индексы диагоналей, параллельных побочной 
# (нумерация начинается с 0), а значения - списки элементов исходного массива, 
# лежащих на соответствующих диагоналях. Решите задачу на примере массива 
# a = np.arange(16).reshape(4, 4), в результате должен получиться словарь
# {0: [0], 1: [1, 4], 2: [2, 5, 8], 3: [3, 6, 9, 12], 4: [7, 10, 13], 5: [11, 14], 6: [15]}.

a = np.arange(16).reshape(4, 4)
N=4
print("Matrix: ")
print(a)
print("")


l=[]
slov={}
i=0; j=0; k=0; p=0

for k in range(2*N-1):     #keys
    
    for i in range (N):
        for j in range (N):
            if i+j == p :
                l.append(a[i,j])
    p += 1
    slov[k] = l
    l = []

print("dict = ")
print(slov)

                    




Matrix: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

dict = 
{0: [0], 1: [1, 4], 2: [2, 5, 8], 3: [3, 6, 9, 12], 4: [7, 10, 13], 5: [11, 14], 6: [15]}


In [15]:
# K-MEANS   in   R^2

def d(a, b, m):
    w=0
    for i in range(m):
        w += (a[i]-b[i])**2
    return w

def middle(a, b, m):
    mid = []
    for i in range(n):
        mid.append((a[i]-b[i])/2)
    return mid


a = np.arange(16).reshape(4, 4)

n=4
m=4
k=3 
l=[]
klasters = {}
spisok = []
ism = 10

for i in range (k):
    p = random.randint(0,n-1)
    l.append(a[p])
    
for i in range (k):
    t=[]
    t.append(l[i])
    spisok.append(t)
    
while ism > 0.1 :
    

    ism = 0
    for i in range (n):  # распределение по кластерам
        mi = 1000
        for j in range(k):
            if d(a[i],l[j],m) < mi :
                mi = d(a[i],l[j],m)
                
                # не проходит
                
      #          for q in range(k-1):
     #               spisok[q].remove(a[i])  #удаление из всех подсписков
      #          spisok[j].append(a[i])      #добавление в ЭТОТ подсписок
            
    for i in range (k):   # пересчет центра масс
        dlina = len(spisok[i])  # 
        mid = spisok[i][0]
    
        for j in range(1, dlina):
            mid = middle(mid, spisok[i][j], m)
        ism += d(mid, l[i], m)
        l[i] = mid


        
    
    
# расстояние точек до каждого из кластеров
# минимальное расстояние обозначит принаблежность кластеру
# счет центра масс
# повтор, пока суммарное изменение не будет меньше порогового epsilon






In [47]:
print(l)
print(l[1])
print(l[1][3])

[array([ 8,  9, 10, 11]), array([12, 13, 14, 15]), array([0, 1, 2, 3])]
[12 13 14 15]
15


In [71]:
d = []
b = []
b.append(1)
d.append(b)
d.append(2)
d[0].append(3)

print (d)

[[1, 3], 2]


NameError: name 'b' is not defined